### ISSUE TITLE
Webviews in the app don't work

### ISSUE THREAD

**Issue by alpha4041** [ahmedtohamy1/SleepZz#1]
![Screenshot_2023-03-14-23-08-24-220_com example sleepzz](https://user-images.githubusercontent.com/88579269/225153494-86ecb755-25b5-406b-be1f-a36d04e81caf.jpg)

**Comment by ahmedtohamy1** [comment]
thanks @alpha4041 , addressed and fixed in b2c88fecd70696f150f918c73af336fcd6d84188
u can download the new release from [here](https://github.com/ahmedtohamy1/SleepZz/releases/tag/Beta-0.1.05)
